// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssTFWqyqX-EPKJP-REtlqxOgL9KJwo_E',
    appId: '1:652921933206:web:7097d262460adae743a1b7',
    messagingSenderId: '652921933206',
    projectId: 'kurakani-e5ec3',
    authDomain: 'kurakani-e5ec3.firebaseapp.com',
    storageBucket: 'kurakani-e5ec3.firebasestorage.app',
    measurementId: 'G-K9DMF53TT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkCbqPjL-bpqn7bg__IE2y3CuMW_XKySY',
    appId: '1:652921933206:android:1f7f82011d00d3eb43a1b7',
    messagingSenderId: '652921933206',
    projectId: 'kurakani-e5ec3',
    storageBucket: 'kurakani-e5ec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKndyusOYfiN8vfaDjYDHbLpOhnP13GF8',
    appId: '1:652921933206:ios:d12a8a4836dc51f443a1b7',
    messagingSenderId: '652921933206',
    projectId: 'kurakani-e5ec3',
    storageBucket: 'kurakani-e5ec3.firebasestorage.app',
    iosBundleId: 'com.example.kurakani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKndyusOYfiN8vfaDjYDHbLpOhnP13GF8',
    appId: '1:652921933206:ios:d12a8a4836dc51f443a1b7',
    messagingSenderId: '652921933206',
    projectId: 'kurakani-e5ec3',
    storageBucket: 'kurakani-e5ec3.firebasestorage.app',
    iosBundleId: 'com.example.kurakani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCssTFWqyqX-EPKJP-REtlqxOgL9KJwo_E',
    appId: '1:652921933206:web:97c232c613a47dd943a1b7',
    messagingSenderId: '652921933206',
    projectId: 'kurakani-e5ec3',
    authDomain: 'kurakani-e5ec3.firebaseapp.com',
    storageBucket: 'kurakani-e5ec3.firebasestorage.app',
    measurementId: 'G-N529BDN03C',
  );
}